=== rei/rei-cedar/src/components/scrollCarousel/examples/Lifestyle/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "content": {
      "type": "object",
      "properties": {
        "heading": {
          "type": "object",
          "properties": {
            "text": {
              "type": "string"
            },
            "level": {
              "type": "string",
              "enum": ["h1", "h2", "h3", "h4", "h5", "h6"]
            },
            "size": {
              "type": "string"
            }
          },
          "required": ["text", "level", "size"]
        }
      },
      "required": ["heading"]
    },
    "slideStyle": {
      "type": "string"
    },
    "slidesVisible": {
      "type": "integer",
      "minimum": 1
    },
    "slides": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "media": {
            "type": "object",
            "properties": {
              "images": {
                "type": "object",
                "properties": {
                  "xs": {
                    "$ref": "#/definitions/imageObject"
                  },
                  "sm": {
                    "$ref": "#/definitions/imageObject"
                  },
                  "md": {
                    "$ref": "#/definitions/imageObject"
                  },
                  "lg": {
                    "$ref": "#/definitions/imageObject"
                  }
                },
                "required": ["xs"]
              },
              "alt": {
                "type": "string"
              },
              "useResizing": {
                "type": "boolean"
              },
              "renderedSizes": {
                "type": "object",
                "properties": {
                  "mobile": {
                    "type": "string"
                  },
                  "desktop": {
                    "type": "string"
                  }
                },
                "required": ["mobile", "desktop"]
              }
            },
            "required": ["images", "alt", "useResizing", "renderedSizes"]
          },
          "cta": {
            "type": "object",
            "properties": {
              "target": {
                "type": "string"
              },
              "text": {
                "type": "string"
              }
            },
            "required": ["target", "text"]
          }
        },
        "required": ["media", "cta"]
      }
    }
  },
  "required": ["content", "slideStyle", "slidesVisible", "slides"],
  "definitions": {
    "imageObject": {
      "type": "object",
      "properties": {
        "caption": {
          "type": ["string", "null"]
        },
        "alt": {
          "type": "string"
        },
        "attribution": {
          "type": ["string", "null"]
        },
        "renditions": {
          "type": "object",
          "properties": {
            "original": {
              "$ref": "#/definitions/imageRendition"
            },
            "wide": {
              "$ref": "#/definitions/imageRendition"
            },
            "vertical": {
              "$ref": "#/definitions/imageRendition"
            }
          },
          "required": ["original"]
        },
        "imageType": {
          "type": "string",
          "enum": ["jpg", "png", "gif", "webp", "svg"]
        }
      },
      "required": ["alt", "renditions", "imageType"]
    },
    "imageRendition": {
      "type": ["object", "null"],
      "properties": {
        "src": {
          "type": "string",
          "pattern": "^(https?|ftp):\\/\\/[\\S]+$"
        },
        "width": {
          "type": "integer",
          "minimum": 1
        },
        "height": {
          "type": "integer",
          "minimum": 1
        }
      },
      "required": ["src", "width", "height"]
    }
  }
}

=== rei/rei-cedar/src/components/scrollCarousel/examples/Lifestyle/mock.json
{
  "content": {
    "heading": {
      "text": "Trending now",
      "level": "h2",
      "size": "sm-standard"
    }
  },
  "slideStyle": "lifestyle-portrait-sm",
  "slidesVisible": 4,
  "slides": [
    {
      "media": {
        "images": {
          "xs": {
            "caption": null,
            "alt": "A runner wearing Vuori apparel.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290255_fs-6-cycling-new_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          },
          "sm": {
            "caption": null,
            "alt": "A runner wearing Vuori apparel.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290255_fs-6-cycling-new_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          },
          "md": {
            "caption": null,
            "alt": "A runner wearing Vuori apparel.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290255_fs-6-cycling-new_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          },
          "lg": {
            "caption": null,
            "alt": "A runner wearing Vuori apparel.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290255_fs-6-cycling-new_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          }
        },
        "alt": "A runner wearing Vuori apparel.",
        "useResizing": true,
        "renderedSizes": {
          "mobile": "33vw",
          "desktop": "25vw"
        }
      },
      "cta": {
        "target": "/b/vuori/c/all",
        "text": "Vuori"
      }
    },
    {
      "media": {
        "images": {
          "xs": {
            "caption": null,
            "alt": "A child getting a piggy back ride from a person in a red jacket.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290279_fs-6-rei-coop_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          },
          "sm": {
            "caption": null,
            "alt": "A child getting a piggy back ride from a person in a red jacket.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290279_fs-6-rei-coop_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          },
          "md": {
            "caption": null,
            "alt": "A child getting a piggy back ride from a person in a red jacket.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290279_fs-6-rei-coop_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          },
          "lg": {
            "caption": null,
            "alt": "A child getting a piggy back ride from a person in a red jacket.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290279_fs-6-rei-coop_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          }
        },
        "alt": "A child getting a piggy back ride from a person in a red jacket.",
        "useResizing": true,
        "renderedSizes": {
          "mobile": "33vw",
          "desktop": "25vw"
        }
      },
      "cta": {
        "target": "/s/gifts-for-him",
        "text": "Father's Day"
      }
    },
    {
      "media": {
        "images": {
          "xs": {
            "caption": null,
            "alt": "A person walks in casual athletic clothing in front of a cactus.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290282_fs-6-gifting_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          },
          "sm": {
            "caption": null,
            "alt": "A person walks in casual athletic clothing in front of a cactus.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290282_fs-6-gifting_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          },
          "md": {
            "caption": null,
            "alt": "A person walks in casual athletic clothing in front of a cactus.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290282_fs-6-gifting_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          },
          "lg": {
            "caption": null,
            "alt": "A person walks in casual athletic clothing in front of a cactus.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290282_fs-6-gifting_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          }
        },
        "alt": "A person walks in casual athletic clothing in front of a cactus.",
        "useResizing": true,
        "renderedSizes": {
          "mobile": "33vw",
          "desktop": "25vw"
        }
      },
      "cta": {
        "target": "/s/gifts-for-them",
        "text": "Grad gifts"
      }
    },
    {
      "media": {
        "images": {
          "xs": {
            "caption": null,
            "alt": "A hat and t-shirt next to an outside with pride R E I Co-op  logo.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290259_fs-6-water-bottles_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          },
          "sm": {
            "caption": null,
            "alt": "A hat and t-shirt next to an outside with pride R E I Co-op  logo.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290259_fs-6-water-bottles_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          },
          "md": {
            "caption": null,
            "alt": "A hat and t-shirt next to an outside with pride R E I Co-op  logo.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290259_fs-6-water-bottles_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          },
          "lg": {
            "caption": null,
            "alt": "A hat and t-shirt next to an outside with pride R E I Co-op  logo.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290259_fs-6-water-bottles_web_lg.jpeg",
                "width": 1200,
                "height": 1600
              },
              "wide": null,
              "vertical": null
            },
            "imageType": "jpg"
          }
        },
        "alt": "A hat and t-shirt next to an outside with pride R E I Co-op  logo.",
        "useResizing": true,
        "renderedSizes": {
          "mobile": "33vw",
          "desktop": "25vw"
        }
      },
      "cta": {
        "target": "/s/outside-with-pride",
        "text": "Pride"
      }
    },
    {
      "media": {
        "images": {
          "xs": {
            "caption": null,
            "alt": "A runner wearing warm weather gear.",
            "attribution": null,
            "renditions": {
              "original": {
                "src": "https://www.rei.com/dam/21290256_fs-6-hiking-footwear-altra_web_lg.jpeg",
                "width": 1200,
